### ISSUE TITLE
[ FEATURE ] PostgreSQL

### ISSUE THREAD

**Issue by nicotravassos** [kasiaizak/filmleb#1]
Hi @kasiaizak,

Thank you for publishing this project idea.
Could you kindly add PostgreSql as a database option?

Not 100% sure if it would be great idea in terms of security?

**Comment by kasiaizak** [comment]
Hi @nicotravassos!
Also, I'm not sure - I'm a beginner front end developer ...;)

**Comment by nicotravassos** [comment]
No worries its probably a bad idea anyway but please keep up the good work :)

**Comment by nicotravassos** [comment]
@kasiaizak remove this as enhancement rather keep the current database structure.
