### ISSUE TITLE
[ FEATURE ] Authentication

### ISSUE THREAD

**Issue by nicotravassos** [kasiaizak/filmleb#2]
Hi @kasiaizak,

Kindly add functionality where you can only add and edit records if logged in.

**Comment by kasiaizak** [comment]
Hi @nicotravassos,
I have it in my plan, but in the undefined future. ;)

**Comment by nicotravassos** [comment]
Interesting @kasiaizak Firebase has its own authentication plugins https://firebase.google.com/pricing
